msgid ""
msgstr ""
"Project-Id-Version: kolibri\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-11-01 22:12-0700\n"
"PO-Revision-Date: 2021-11-02 05:29\n"
"Last-Translator: \n"
"Language-Team: Arabic\n"
"Language: ar_SA\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=6; plural=(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5);\n"
"X-Crowdin-Project: kolibri\n"
"X-Crowdin-Project-ID: 201933\n"
"X-Crowdin-Language: ar\n"
"X-Crowdin-File: /release-v0.15.x/django.po\n"
"X-Crowdin-File-ID: 4105\n"

#: core/auth/constants/commands_errors.py:17
msgid "Unexpected exception [{}]: {}"
msgstr "استثناء غير متوقع [{}]: {}"

#: core/auth/constants/commands_errors.py:20
msgctxt "Error report message when the allowed number of digits has been exceeded."
msgid "Content of cell '{}' is too long"
msgstr "محتوى الخلية '{}' طويل للغاية"

#: core/auth/constants/commands_errors.py:24
msgctxt "Error report message when the cell contains an improper data format."
msgid "Content of cell '{}' is not valid"
msgstr "محتوى الخلية '{}' غير صالح"

#: core/auth/constants/commands_errors.py:26
msgid "Duplicated username"
msgstr "اسم مستخدم مكرر"

#: core/auth/constants/commands_errors.py:28
#: core/auth/management/commands/bulkimportusers.py:85
msgid "Username only can contain characters, numbers and underscores"
msgstr "يمكن لاسم المستخدم أن يحتوي فقط على أحرف وأرقام ومحارف سفلية"

#: core/auth/constants/commands_errors.py:30
msgid "The column '{}' is required"
msgstr "العمود '{}' مطلوب"

#: core/auth/constants/commands_errors.py:31
msgid "Mix of valid and/or invalid header labels found in first row"
msgstr "تم العثور على مزيج من تسميات صالحة/ أو غير صالحة في الصف الأول"

#: core/auth/constants/commands_errors.py:33
msgid "No default facility exists. Make sure to set up a facility on the device before running this command"
msgstr "لا يوجد مرفق تعليمي افتراضي. تأكد من إعداد مرفق تعليمي على الجهاز قبل تشغيل هذا الأمر"

#: core/auth/constants/commands_errors.py:35
#: core/auth/management/commands/bulkimportusers.py:99
msgid "Error trying to read csv file: {}"
msgstr "خطأ أثناء محاولة قراءة ملف csv: {}"

#: core/auth/constants/commands_errors.py:36
#: core/auth/management/commands/bulkimportusers.py:100
msgid "Error trying to write csv file: {}"
msgstr "خطأ أثناء محاولة كتابة ملف csv: {}"

#: core/auth/management/commands/bulkexportusers.py:42
#: core/auth/management/commands/bulkexportusers.py:124
msgid "Database ID ({})"
msgstr "معرف قاعدة البيانات ({})"

#: core/auth/management/commands/bulkexportusers.py:43
#: core/auth/management/commands/bulkexportusers.py:125
msgid "Username ({})"
msgstr "اسم المستخدم ({})"

#: core/auth/management/commands/bulkexportusers.py:44
#: core/auth/management/commands/bulkexportusers.py:126
msgid "Password ({})"
msgstr "كلمة المرور ({})"

#: core/auth/management/commands/bulkexportusers.py:45
#: core/auth/management/commands/bulkexportusers.py:127
msgid "Full name ({})"
msgstr "الاسم الكامل ({})"

#: core/auth/management/commands/bulkexportusers.py:50
msgctxt "CSV column header for the type of user: ADMIN, LEARNER, COACH..."
msgid "User type ({})"
msgstr "نوع المستخدم ({})"

#: core/auth/management/commands/bulkexportusers.py:53
#: core/auth/management/commands/bulkexportusers.py:135
msgid "Identifier ({})"
msgstr "المعرّف ({})"

#: core/auth/management/commands/bulkexportusers.py:54
#: core/auth/management/commands/bulkexportusers.py:136
msgid "Birth year ({})"
msgstr "سنة الميلاد ({})"

#: core/auth/management/commands/bulkexportusers.py:55
#: core/auth/management/commands/bulkexportusers.py:137
msgid "Gender ({})"
msgstr "الجنس ({})"

#: core/auth/management/commands/bulkexportusers.py:60
msgctxt "CSV column header for the list of classrooms names where the learner is going to be enrolled"
msgid "Learner enrollment ({})"
msgstr "إدراج متعلم ({})"

#: core/auth/management/commands/bulkexportusers.py:67
msgctxt "CSV column header for the list of classrooms names where the tutor is going to be a coach"
msgid "Coach assignment ({})"
msgstr "تعيين مدرب ({})"

#: core/auth/management/commands/bulkexportusers.py:132
msgctxt "CSV header for the type of user: ADMIN, LEARNER, COACH..."
msgid "User type ({})"
msgstr "نوع المستخدم ({})"

#: core/auth/management/commands/bulkexportusers.py:142
msgctxt "CSV file header for the list of classrooms names where the learner is going to be enrolled"
msgid "Learner enrollment ({})"
msgstr "إدراج متعلم ({})"

#: core/auth/management/commands/bulkexportusers.py:149
msgctxt "CSV file header for the list of classrooms names where the tutor is going to be a coach"
msgid "Coach assignment ({})"
msgstr "تعيين مدرب ({})"

#: core/auth/management/commands/bulkimportusers.py:76
msgctxt "Error message that might appear when there's a programming error importing a CSV file"
msgid "Unexpected error [{}]: {}"
msgstr "خطأ غير متوقع [{}]: {}"

#: core/auth/management/commands/bulkimportusers.py:80
msgctxt "Error when the command is executed in the Terminal (command prompt)"
msgid "Value in column '{}' has too many characters"
msgstr "القيمة المدرجة في العمود '{}' تحتوي على محارف كثيرة جدا"

#: core/auth/management/commands/bulkimportusers.py:82
msgid "Value in column '{}' not valid"
msgstr "القيمة في العمود '{}' غير صالحة"

#: core/auth/management/commands/bulkimportusers.py:83
msgid "Username is duplicated"
msgstr "اسم المستخدم مكرر"

#: core/auth/management/commands/bulkimportusers.py:89
msgctxt "Error message indicating that the CSV file selected for import is missing a required column"
msgid "The column '{}' is required"
msgstr "العمود '{}' مطلوب"

#: core/auth/management/commands/bulkimportusers.py:93
msgctxt "Error message indicating that one column header in the CSV file selected for import is missing or incorrect"
msgid "Incorrect header label found in the first row"
msgstr "تم العثور على ترويسة غير صالحة في الصف الأول"

#: core/auth/management/commands/bulkimportusers.py:97
msgctxt "Error when the command is executed in the Terminal (command prompt)"
msgid "No default facility exists. Make sure to set up a facility on the  device before importing users and classes"
msgstr "لا يوجد مرفق تعليمي افتراضي. تأكد من إعداد مرفق تعليمي على الجهاز قبل استيراد المستخدمين والصفوف"

#: core/auth/management/commands/bulkimportusers.py:102
msgid "The password field is required. To leave the password unchanged in existing users, insert an asterisk (*)"
msgstr "حقل كلمة المرور مطلوب. لترك كلمة المرور دون تغيير في المستخدمين الحاليين، قم بإدخال علامة نجمية (*)"

#: core/auth/management/commands/bulkimportusers.py:105
msgid "Cannot update user with ID: '{}' because no user with that database ID exists in this facility"
msgstr "لا يمكن تحديث المستخدم باستخدام المعرف: '{}' لعدم وجود مستخدم لمعرف قاعدة البيانات هذه في هذا المرفق التعليمي"

#: core/auth/management/commands/bulkimportusers.py:107
msgid "Database ID is not valid"
msgstr "معرف قاعدة البيانات غير صالح"

#: core/content/api.py:170
msgid "Resource"
msgstr "المصدر"

#: core/content/api.py:1327
msgid "The requested channel does not exist on the content server"
msgstr "القناة التعليمية المطلوبة غير موجودة على خادم المحتوى"

#: core/content/models.py:252
msgid "Unknown format"
msgstr "صيغة غير معروفة"

#: core/device/serializers.py:36
msgid "Language is not supported by Kolibri"
msgstr "هذه اللغة غير مدعومة حالياً على كوليبري"

#: core/logger/csv_export.py:205
msgctxt "Default name for the exported CSV file with content session logs. Please keep the underscores between words in the translation"
msgid "content_session_logs"
msgstr "سجلات_جلسة_المحتوى"

#: core/logger/csv_export.py:215
msgctxt "Default name for the exported CSV file with content summary logs. Please keep the underscores between words in the translation"
msgid "content_summary_logs"
msgstr "سجلات_ملخص_المحتوى"

#: core/tasks/api.py:82
msgid "There was a network error."
msgstr "حصل خطأ ما في الشبكة."

#: core/tasks/api.py:84
msgid "There was a disk access error."
msgstr "حصل خطأ ما أثناء محاولة الوصول إلى القرص التخزيني."

#: core/tasks/api.py:86
msgid "There was an unknown error."
msgstr "حصل خطأ غير معروف."

#: core/templates/kolibri/base.html:13
#: core/templates/kolibri/unsupported_browser.html:13
msgid "Kolibri"
msgstr "كوليبري"

#: core/templates/kolibri/unsupported_browser.html:42
msgid "Unsupported browser"
msgstr "متصفح غير مدعوم"

#: core/templates/kolibri/unsupported_browser.html:43
msgid "Sorry, your browser version is not supported."
msgstr "نعتذر، النسخة الحالية لمتصفحك غير مدعومة."

#: core/templates/kolibri/unsupported_browser.html:44
msgid "To use Kolibri, we recommend using Firefox or Chrome."
msgstr "لاستخدام كوليبري، ننصح باستخدام متصفح فايرفوكس أو متصفح كروم."

#: core/templates/kolibri/unsupported_browser.html:45
msgid "You can also try updating your current browser."
msgstr "يمكنك أيضاً محاولة تحديث متصفحك الحالي."

#: core/views.py:168
msgid "No appropriate redirect pages found. It is likely that Kolibri is badly configured"
msgstr "لم يتم العثور على صفحات. يبدو أنّ عملية تهيئة منصة كوليبري لم تتم بالشكل الصحيح"

#: plugins/facility/views.py:52
msgctxt "Default name for the exported CSV file of facility user data. Please keep the underscore between words in the translation"
msgid "users_{}"
msgstr "المستخدمون_{}"

