msgid ""
msgstr ""
"Project-Id-Version: kolibri\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-07-29 15:05-0700\n"
"PO-Revision-Date: 2021-08-13 22:36\n"
"Last-Translator: \n"
"Language-Team: Yoruba\n"
"Language: yo_NG\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Crowdin-Project: kolibri\n"
"X-Crowdin-Project-ID: 201933\n"
"X-Crowdin-Language: yo\n"
"X-Crowdin-File: /release-v0.15.x/django.po\n"
"X-Crowdin-File-ID: 4105\n"

#: core/auth/constants/commands_errors.py:17
msgid "Unexpected exception [{}]: {}"
msgstr "Ìyàsọ́tó àìròtẹ́lẹ̀ [{}]: {}"

#: core/auth/constants/commands_errors.py:20
msgctxt "Error report message when the allowed number of digits has been exceeded."
msgid "Content of cell '{}' is too long"
msgstr "Àkoonú sẹ́ẹ̀lì '{}' ti gun jù"

#: core/auth/constants/commands_errors.py:24
msgctxt "Error report message when the cell contains an improper data format."
msgid "Content of cell '{}' is not valid"
msgstr "Àkoonú sẹ́ẹ̀lì '{}' kò péye"

#: core/auth/constants/commands_errors.py:26
msgid "Duplicated username"
msgstr "Ìsọdiméjì orúkọ aṣàmúlò"

#: core/auth/constants/commands_errors.py:28
#: core/auth/management/commands/bulkimportusers.py:85
msgid "Username only can contain characters, numbers and underscores"
msgstr "Orúkọ aṣàmúlò nikan ni o le ni àwọn ẹyọ ọ̀rọ̀, nọmba ati àwọn ìlà abẹ́"

#: core/auth/constants/commands_errors.py:30
msgid "The column '{}' is required"
msgstr "Nílò ọwọ̀n '{}' náà"

#: core/auth/constants/commands_errors.py:31
msgid "Mix of valid and/or invalid header labels found in first row"
msgstr "Àdàpọ̀ àkọlé ìlà abẹ́gbẹ́mu àti/tàbí aláìbẹ́gbẹ́mu ni a rí ní ìlà ìbú àkọkọ́"

#: core/auth/constants/commands_errors.py:33
msgid "No default facility exists. Make sure to set up a facility on the device before running this command"
msgstr "Ko si ohun elo àkùnàyàn. Rii daju lati ṣeto ohun elo lori ẹrọ ṣaaju ṣiṣe aṣẹ yii"

#: core/auth/constants/commands_errors.py:35
#: core/auth/management/commands/bulkimportusers.py:99
msgid "Error trying to read csv file: {}"
msgstr "Àṣìṣe kíka fáìlì csv: {}"

#: core/auth/constants/commands_errors.py:36
#: core/auth/management/commands/bulkimportusers.py:100
msgid "Error trying to write csv file: {}"
msgstr "Àṣìṣe kíkọ fáìlì csv: {}"

#: core/auth/management/commands/bulkexportusers.py:42
#: core/auth/management/commands/bulkexportusers.py:124
msgid "Database ID ({})"
msgstr "Àkójọdátà ÌDÁNIMỌ̀ ({})"

#: core/auth/management/commands/bulkexportusers.py:43
#: core/auth/management/commands/bulkexportusers.py:125
msgid "Username ({})"
msgstr "Orúkọ aṣàmúlò ({})"

#: core/auth/management/commands/bulkexportusers.py:44
#: core/auth/management/commands/bulkexportusers.py:126
msgid "Password ({})"
msgstr "Ọ̀rọ̀ aṣínà ({})"

#: core/auth/management/commands/bulkexportusers.py:45
#: core/auth/management/commands/bulkexportusers.py:127
msgid "Full name ({})"
msgstr "Orúkọ ní kíkún ({})"

#: core/auth/management/commands/bulkexportusers.py:50
msgctxt "CSV column header for the type of user: ADMIN, LEARNER, COACH..."
msgid "User type ({})"
msgstr "Irúfẹ́ aṣàmúlò ({})"

#: core/auth/management/commands/bulkexportusers.py:53
#: core/auth/management/commands/bulkexportusers.py:135
msgid "Identifier ({})"
msgstr "Àfidámọ̀ ({})"

#: core/auth/management/commands/bulkexportusers.py:54
#: core/auth/management/commands/bulkexportusers.py:136
msgid "Birth year ({})"
msgstr "Ọdún ìbí ({})"

#: core/auth/management/commands/bulkexportusers.py:55
#: core/auth/management/commands/bulkexportusers.py:137
msgid "Gender ({})"
msgstr "Obí tàbí akọ ({})"

#: core/auth/management/commands/bulkexportusers.py:60
msgctxt "CSV column header for the list of classrooms names where the learner is going to be enrolled"
msgid "Learner enrollment ({})"
msgstr "Ìforúkọsílẹ̀ akẹ́kọ̀ọ́ ({})"

#: core/auth/management/commands/bulkexportusers.py:67
msgctxt "CSV column header for the list of classrooms names where the tutor is going to be a coach"
msgid "Coach assignment ({})"
msgstr "Iṣẹ́ àmúrelé olùkọ́ ({})"

#: core/auth/management/commands/bulkexportusers.py:132
msgctxt "CSV header for the type of user: ADMIN, LEARNER, COACH..."
msgid "User type ({})"
msgstr "Irúfẹ́ aṣàmúlò ({})"

#: core/auth/management/commands/bulkexportusers.py:142
msgctxt "CSV file header for the list of classrooms names where the learner is going to be enrolled"
msgid "Learner enrollment ({})"
msgstr "Ìforúkọsílẹ̀ akẹ́kọ̀ọ́ ({})"

#: core/auth/management/commands/bulkexportusers.py:149
msgctxt "CSV file header for the list of classrooms names where the tutor is going to be a coach"
msgid "Coach assignment ({})"
msgstr "Iṣẹ́ àmúrelé olùkọ́ ({})"

#: core/auth/management/commands/bulkimportusers.py:76
msgctxt "Error message that might appear when there's a programming error importing a CSV file"
msgid "Unexpected error [{}]: {}"
msgstr "Ìṣìṣe àìròtẹ́lẹ̀ [{}]: {}"

#: core/auth/management/commands/bulkimportusers.py:80
msgctxt "Error when the command is executed in the Terminal (command prompt)"
msgid "Value in column '{}' has too many characters"
msgstr "Iye nǹkan inú ìlà òró '{}' ní àpọ̀jù ẹyọ ọ̀rọ̀"

#: core/auth/management/commands/bulkimportusers.py:82
msgid "Invalid value in column '{}'"
msgstr "Àìtọ̀ iye nǹkan inú ọwọ̀n '{}'"

#: core/auth/management/commands/bulkimportusers.py:83
msgid "Username is duplicated"
msgstr "Ìṣenírúméjí orúkọ-òǹṣàmúlò"

#: core/auth/management/commands/bulkimportusers.py:89
msgctxt "Error message indicating that the CSV file selected for import is missing a required column"
msgid "The column '{}' is required"
msgstr "Nílò ọwọ̀n '{}' náà"

#: core/auth/management/commands/bulkimportusers.py:93
msgctxt "Error message indicating that one column header in the CSV file selected for import is missing or incorrect"
msgid "Invalid header label found in the first row"
msgstr "Àìtọ̀ ìsààmì ọ̀rọ̀-aṣorí wà nínú ìlà àkọ́kọ́"

#: core/auth/management/commands/bulkimportusers.py:97
msgctxt "Error when the command is executed in the Terminal (command prompt)"
msgid "No default facility exists. Make sure to set up a facility on the  device before importing users and classes"
msgstr "Ko si ohun elo àkùnàyàn. Rii daju lati ṣeto ohun elo lori ẹrọ ṣaaju agbewọle awọn oluṣamulo ati awọn kilaasi"

#: core/auth/management/commands/bulkimportusers.py:102
msgid "The password field is required. To leave the password unchanged in existing users, insert an asterisk (*)"
msgstr "A nílò ọ̀rọ̀-aṣínà. Láti fi ọ̀rọ̀ aṣínà sílẹ̀ láìyípadà ní àwọn olùṣàmúlò tí ó wà tẹ́lẹ̀, lo àmì ìràwọ̀ (*)"

#: core/auth/management/commands/bulkimportusers.py:105
msgid "Cannot update user with ID: '{}' because no user with that database ID exists in this facility"
msgstr "Kòle ṣàfikún àwọn ìrísí olùlò pẹ̀lú ID: '{}' nítorí kòsí olùṣàmúlò tí ó ní ID àkójọpọ̀ détà nínu ohun elò yìí"

#: core/auth/management/commands/bulkimportusers.py:107
msgid "Database ID is not valid"
msgstr "Ibùgbéìwífúnalálàyé ìdánimọ̀ ID kò kòjú òṣùwọ̀n"

#: core/content/api.py:152
msgid "Resource"
msgstr "Ohun èlò"

#: core/content/api.py:1269
msgid "The requested channel does not exist on the content server"
msgstr "Ìkànnì yìí kò sí lóri íntánẹ́ẹ̀tì"

#: core/content/models.py:220
msgid "Unknown format"
msgstr "Fọ́máàtì yìí kò sí"

#: core/device/serializers.py:41
msgid "Language is not supported by Kolibri"
msgstr "Kò sí èdè yìí lorí Kolibri"

#: core/logger/csv_export.py:204
msgctxt "Default name for the exported CSV file with content session logs. Please keep the underscores between words in the translation"
msgid "content_session_logs"
msgstr "àkóónú_sáà_àwọn-àkọsílẹ̀-iṣẹ́"

#: core/logger/csv_export.py:214
msgctxt "Default name for the exported CSV file with content summary logs. Please keep the underscores between words in the translation"
msgid "content_summary_logs"
msgstr "àkóónù_níṣókí_àwọn-àkọsílẹ̀-iṣẹ́"

#: core/tasks/api.py:82
msgid "There was a network error."
msgstr "Ìńtánẹ́ẹ̀tì ń ṣe ségesège."

#: core/tasks/api.py:84
msgid "There was a disk access error."
msgstr "Àṣìṣe ìráàyèsì dísíkì wáyé."

#: core/tasks/api.py:86
msgid "There was an unknown error."
msgstr "Àṣìṣe wáyé."

#: core/templates/kolibri/base.html:13
#: core/templates/kolibri/unsupported_browser.html:13
msgid "Kolibri"
msgstr "Kolibri"

#: core/templates/kolibri/unsupported_browser.html:42
msgid "Unsupported browser"
msgstr "Ìlujá ìwádìí yìí kò lè ṣiṣẹ́"

#: core/templates/kolibri/unsupported_browser.html:43
msgid "Sorry, your browser version is not supported."
msgstr "Má bínú, ìlujá ìwádìí tí ò ń lò kò lè ṣiṣẹ́."

#: core/templates/kolibri/unsupported_browser.html:44
msgid "To use Kolibri, we recommend using Firefox or Chrome."
msgstr "Láti lo Kolibri, a dàbá pé kó o lo Firefox tàbí Chrome."

#: core/templates/kolibri/unsupported_browser.html:45
msgid "You can also try updating your current browser."
msgstr "O tún lè gbìyànjú láti lo ìlujá ìwádìí tuntun."

#: core/views.py:161
msgid "No appropriate redirect pages found. It is likely that Kolibri is badly configured"
msgstr "Kò sí àwọn ojú ewé tí ò ń wá. Ó ṣeé ṣe kó jẹ́ pé ìkànnì Kolibri kò ṣiṣẹ́ bó ṣe yẹ"

#: plugins/facility/views.py:52
msgctxt "Default name for the exported CSV file of facility user data. Please keep the underscore between words in the translation"
msgid "users_{}"
msgstr "àwọn olùṣàmúlò_{}"

