msgid ""
msgstr ""
"Project-Id-Version: kolibri\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-07-29 15:05-0700\n"
"PO-Revision-Date: 2021-08-13 22:36\n"
"Last-Translator: \n"
"Language-Team: Burmese\n"
"Language: my_MM\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Crowdin-Project: kolibri\n"
"X-Crowdin-Project-ID: 201933\n"
"X-Crowdin-Language: my\n"
"X-Crowdin-File: /release-v0.15.x/django.po\n"
"X-Crowdin-File-ID: 4105\n"

#: core/auth/constants/commands_errors.py:17
msgid "Unexpected exception [{}]: {}"
msgstr "မမျှော်လင့်ထားသည့်ခြွင်းချက် [{}]: {}"

#: core/auth/constants/commands_errors.py:20
msgctxt "Error report message when the allowed number of digits has been exceeded."
msgid "Content of cell '{}' is too long"
msgstr "ဇယားကွက်၏အကြောင်းအရာ '{}' ကရှည်လွန်းသည်"

#: core/auth/constants/commands_errors.py:24
msgctxt "Error report message when the cell contains an improper data format."
msgid "Content of cell '{}' is not valid"
msgstr "ဇယားကွက်၏အကြောင်းအရာ '{}' ကမရှိပါ"

#: core/auth/constants/commands_errors.py:26
msgid "Duplicated username"
msgstr "ထပ်နေသောအသုံးပြုသူအမည်"

#: core/auth/constants/commands_errors.py:28
#: core/auth/management/commands/bulkimportusers.py:85
msgid "Username only can contain characters, numbers and underscores"
msgstr "အသုံးပြုသူအမည်တွင် အက္ခရာများ၊ ကိန်းဂဏန်းများနှင့် အောက်မျဉ်းများသာ ထည့်နိုင်သည်"

#: core/auth/constants/commands_errors.py:30
msgid "The column '{}' is required"
msgstr "ကော်လံ '{}' ကလိုအပ်သည်"

#: core/auth/constants/commands_errors.py:31
msgid "Mix of valid and/or invalid header labels found in first row"
msgstr "ပထမအတန်းတွင် ရှိသောနှင့်မရှိသောလေဘယ်များရောနှောနေသည်ကိုတွေ့ရသည်"

#: core/auth/constants/commands_errors.py:33
msgid "No default facility exists. Make sure to set up a facility on the device before running this command"
msgstr "မူရင်းအထောက်အပံ့မရှိပါ။ ဒီညွှန်ကြားချက်ကိုမလုပ်ဆောင်မီ ထိုပစ္စည်းတွင်ထောက်ပံ့မှုတစ်ခုကိုဖန်တီးပြီးတာ သေချာပါစေ။"

#: core/auth/constants/commands_errors.py:35
#: core/auth/management/commands/bulkimportusers.py:99
msgid "Error trying to read csv file: {}"
msgstr "csv ဖိုင် {} ကိုဖတ်ရန် အမှားဖြစ်နေသည်"

#: core/auth/constants/commands_errors.py:36
#: core/auth/management/commands/bulkimportusers.py:100
msgid "Error trying to write csv file: {}"
msgstr "csv ဖိုင် {} ကိုရေးရန် အမှားဖြစ်နေသည်"

#: core/auth/management/commands/bulkexportusers.py:42
#: core/auth/management/commands/bulkexportusers.py:124
msgid "Database ID ({})"
msgstr "ဒေတာဘေ့(စ်) မှတ်ပုံတင် ({})"

#: core/auth/management/commands/bulkexportusers.py:43
#: core/auth/management/commands/bulkexportusers.py:125
msgid "Username ({})"
msgstr "အသုံးပြုသူအမည် ({})"

#: core/auth/management/commands/bulkexportusers.py:44
#: core/auth/management/commands/bulkexportusers.py:126
msgid "Password ({})"
msgstr "စကားဝှက် ({})"

#: core/auth/management/commands/bulkexportusers.py:45
#: core/auth/management/commands/bulkexportusers.py:127
msgid "Full name ({})"
msgstr "အမည်အပြည့်အစုံ ({})"

#: core/auth/management/commands/bulkexportusers.py:50
msgctxt "CSV column header for the type of user: ADMIN, LEARNER, COACH..."
msgid "User type ({})"
msgstr "အသုံးပြုသူအမျိုးအစား ({})"

#: core/auth/management/commands/bulkexportusers.py:53
#: core/auth/management/commands/bulkexportusers.py:135
msgid "Identifier ({})"
msgstr "အသိအမှတ်ပြုသူ ({})"

#: core/auth/management/commands/bulkexportusers.py:54
#: core/auth/management/commands/bulkexportusers.py:136
msgid "Birth year ({})"
msgstr "မွေးသည့်နှစ် ({})"

#: core/auth/management/commands/bulkexportusers.py:55
#: core/auth/management/commands/bulkexportusers.py:137
msgid "Gender ({})"
msgstr "လိင်အမျိုးအစား ({})"

#: core/auth/management/commands/bulkexportusers.py:60
msgctxt "CSV column header for the list of classrooms names where the learner is going to be enrolled"
msgid "Learner enrollment ({})"
msgstr "သင်တန်းသားစာရင်းသွင်းမှု ({})"

#: core/auth/management/commands/bulkexportusers.py:67
msgctxt "CSV column header for the list of classrooms names where the tutor is going to be a coach"
msgid "Coach assignment ({})"
msgstr "နည်းပြတာဝန်ချထားမှု ({})"

#: core/auth/management/commands/bulkexportusers.py:132
msgctxt "CSV header for the type of user: ADMIN, LEARNER, COACH..."
msgid "User type ({})"
msgstr "အသုံးပြုသူအမျိုးအစား ({})"

#: core/auth/management/commands/bulkexportusers.py:142
msgctxt "CSV file header for the list of classrooms names where the learner is going to be enrolled"
msgid "Learner enrollment ({})"
msgstr "သင်တန်းသားစာရင်းသွင်းမှု ({})"

#: core/auth/management/commands/bulkexportusers.py:149
msgctxt "CSV file header for the list of classrooms names where the tutor is going to be a coach"
msgid "Coach assignment ({})"
msgstr "နည်းပြတာဝန်ချထားမှု ({})"

#: core/auth/management/commands/bulkimportusers.py:76
msgctxt "Error message that might appear when there's a programming error importing a CSV file"
msgid "Unexpected error [{}]: {}"
msgstr "မမျှော်လင့်သည့်အမှား [{}]: {}"

#: core/auth/management/commands/bulkimportusers.py:80
msgctxt "Error when the command is executed in the Terminal (command prompt)"
msgid "Value in column '{}' has too many characters"
msgstr "'{}' ထဲတွင်ပါသောတန်ဖိုးက အက္ခရာများလွန်းသည်"

#: core/auth/management/commands/bulkimportusers.py:82
msgid "Invalid value in column '{}'"
msgstr "ကော်လံ '{}' ရှိတန်ဖိုးက မရှိပါ"

#: core/auth/management/commands/bulkimportusers.py:83
msgid "Username is duplicated"
msgstr "အသုံးပြုသူအမည်ထပ်နေသည်"

#: core/auth/management/commands/bulkimportusers.py:89
msgctxt "Error message indicating that the CSV file selected for import is missing a required column"
msgid "The column '{}' is required"
msgstr "ကော်လံ '{}' ကလိုအပ်သည်"

#: core/auth/management/commands/bulkimportusers.py:93
msgctxt "Error message indicating that one column header in the CSV file selected for import is missing or incorrect"
msgid "Invalid header label found in the first row"
msgstr "မသတ်မှတ်ထားသောခေါင်းစီးလေဘယ်ကို ပထမအတန်းတွင်တွေ့သည်"

#: core/auth/management/commands/bulkimportusers.py:97
msgctxt "Error when the command is executed in the Terminal (command prompt)"
msgid "No default facility exists. Make sure to set up a facility on the  device before importing users and classes"
msgstr "မူရင်းအထောက်အပံ့မရှိပါ။ အသုံးပြုသူများနှင့်အတန်းများကိုမထည့်သွင်းမီ ထိုပစ္စည်းတွင်ထောက်ပံ့မှုတစ်ခုကိုဖန်တီးပြီးတာ သေချာပါစေ။"

#: core/auth/management/commands/bulkimportusers.py:102
msgid "The password field is required. To leave the password unchanged in existing users, insert an asterisk (*)"
msgstr "စကားဝှက်နေရာကိုဖြည့်သွင်းရန်လိုအပ်သည်။ ရှိပြီးသားအသုံးပြုသူများတွင် စကားဝှက်ကိုမပြောင်းလဲစေရန် ကြယ်ပွင့်ပုံစံ(*)ထည့်ပါ"

#: core/auth/management/commands/bulkimportusers.py:105
msgid "Cannot update user with ID: '{}' because no user with that database ID exists in this facility"
msgstr "ယခုထောက်ပံ့မှုတွင် အဆိုပါဒေတာဘေ့(စ်)မှတ်ပုံတင်နှင့်အသုံးပြုသူမရှိသည့်အတွက် မှတ်ပုံတင် {} နှင့်အသုံးပြုသူကို အဆင့်မမြှင့်နိုင်ပါ"

#: core/auth/management/commands/bulkimportusers.py:107
msgid "Database ID is not valid"
msgstr "ဒေတာဘေ့(စ်)မှတ်ပုံတင် မရှိပါ"

#: core/content/api.py:152
msgid "Resource"
msgstr "ရင်းမြစ်"

#: core/content/api.py:1269
msgid "The requested channel does not exist on the content server"
msgstr "တောင်းဆိုသော ချယ်နယ်သည် မာတိကာဆာဗာတွင် မရှိပါ"

#: core/content/models.py:220
msgid "Unknown format"
msgstr "Format အမြိုးအစားမသိပါ၊"

#: core/device/serializers.py:41
msgid "Language is not supported by Kolibri"
msgstr "Kolibri မှ မထောက်ပံ့ထားသော ဘာသာစကား"

#: core/logger/csv_export.py:204
msgctxt "Default name for the exported CSV file with content session logs. Please keep the underscores between words in the translation"
msgid "content_session_logs"
msgstr "အကြောင်းအရာကဏ္ဍမှတ်တမ်းများ"

#: core/logger/csv_export.py:214
msgctxt "Default name for the exported CSV file with content summary logs. Please keep the underscores between words in the translation"
msgid "content_summary_logs"
msgstr "အကြောင်းအရာပေါင်းချုပ်မှတ်တမ်းများ"

#: core/tasks/api.py:82
msgid "There was a network error."
msgstr "ကွန်ရက်အမှားအယွင်း ရှိပါသည်"

#: core/tasks/api.py:84
msgid "There was a disk access error."
msgstr "Disk  အသုံးပြုမှု ချို့ယွင်းချက်ရှိခဲ့သည်"

#: core/tasks/api.py:86
msgid "There was an unknown error."
msgstr "၎င်းတွင် မသိရှိသော ချို့ယွင်းချက် များရှိခဲ့သည်"

#: core/templates/kolibri/base.html:13
#: core/templates/kolibri/unsupported_browser.html:13
msgid "Kolibri"
msgstr "Kolibri"

#: core/templates/kolibri/unsupported_browser.html:42
msgid "Unsupported browser"
msgstr "အထောက်အပံ့ မပေးသော browser ဖြစ် နေသည်"

#: core/templates/kolibri/unsupported_browser.html:43
msgid "Sorry, your browser version is not supported."
msgstr "ဆောရီးပါ သင်၏ browser ဗားရှင်းအတွက် မထောက်ပံ့ထားပါ "

#: core/templates/kolibri/unsupported_browser.html:44
msgid "To use Kolibri, we recommend using Firefox or Chrome."
msgstr "Kolibri အသုံးပြုရန် Firefox သို့မဟုတ် Chrome ကိုသုံးရန် အကြံပေးလိုသည်"

#: core/templates/kolibri/unsupported_browser.html:45
msgid "You can also try updating your current browser."
msgstr "သင်၏ ယခု browser ကို အသစ်မွမ်းမံရန်လည်းကြိုးစားနိုင်ပါသည်"

#: core/views.py:161
msgid "No appropriate redirect pages found. It is likely that Kolibri is badly configured"
msgstr "သင့်တော်သော ချိတ်ဆက်ပေးမည့်စာမျက်နှာကိုမတွေ့ပါ။ Kolibri ကိုမှားယွင်းစွာ ပြင်ဆင်ထားသလိုဖြစ်နေသည်"

#: plugins/facility/views.py:52
msgctxt "Default name for the exported CSV file of facility user data. Please keep the underscore between words in the translation"
msgid "users_{}"
msgstr "အသုံးပြုသူများ_{}"

